# Site settings
title: CAIXA-PRETA
email: "caixapreta@voltdata.info"
description: "Um podcast que desvenda o impacto da tecnologia na sociedade"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://cxpx.com.br" # the base hostname & protocol for your site
twitter_username: caixapretacast
github_username: voltdatalab
permalink: /:title:output_ext

# Build settings
#markdown: redcarpet
#markdown_ext:  markdown,mkdown,mkdn,mkd,md

#redcarpet:
#  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]
